### ISSUE TITLE
API Security during development

### ISSUE THREAD

**Issue by patricksan** [cloud-erp-school-system/backend#17]
We should investigate a way to improve development speed and avoid Keycloack authentication.
Probably a profile like `dev` would to the job.

@Aurrix could you kindly check that, please?

**Comment by Aurrix** [comment]
@patricksan I've created 2 profiles dev and staging
It solves problems for the front-end, but it still gives some overhead for backend developers.
Because we cannot rely now on principals. I am not sure if we gonna use those anyway, but I imagine we would want at some point to use authenticated user`s data. That might be a problem because we will have to mock that part somehow.

**Comment by Aurrix** [comment]
Anyway please take a look and let me know what u think
